<?php
return array(
    'year_events' => 'This years events',
    'more_info' => 'Read more information >',
    'all_news' => 'Read all latest news',
    'all_dates' => 'View all dates >',
    'phone' => 'Phone:',
    'email' => 'Email:',
    'address' => 'Address:',
    'jan' => 'Jan:',
    'gary' => 'Gary:',
    'e' => 'E:',
    't' => 'T:',
    'find_more' => 'find out more',
    'month_dates' => 'This month dates',
    'date' => 'Date:',
    'venue' => 'Venue:',
    'time' => 'Time:',
    'view_details' => 'View all details',
    'sign_up' => 'Sign up to course',
    'back_list' => 'Back to full list',
    'back_to_news' => '&lt; Back to Latest Blog articles',
    'prev' => '&lt; Previous',
    'next' => 'Next &gt;',
    'submit' => 'Submit',
    'thank_subscribe' => 'Thank you for subscribing.',
    'subscribe' => 'Subscribe',
    's_name' => 'Your name',
    's_email' => 'Your email',
    'popular_posts' => 'Popular posts'
);