<?php
return array(
    'address' => 'Address:',
    'age' => 'Child\'s Age',
    'all_dates' => 'View all dates >',
    'all_news' => 'Read all latest news',

    'back_list' => 'Back to full list',
    'back_to_news' => '&lt; Back to Latest Blog articles',
    'booking_complete' => 'Booking complete',
    'booking_confirmed' => 'Booking confirmed.',
    'booking_id' => 'Booking ID',

    'c_contact_name' => 'Contact name',
    'c_dob' => 'Date of Birth of Child',
    'c_email' => 'Email',
    'c_landline' => 'Landline number',
    'c_mobile' => 'Mobile number',
    'c_name' => 'Surname and Initials of child',
    'c_school' => 'School child currently attends',
    'c_wished_name' => 'Name child wishes to be called',
    'c_yr' => 'Year group child is in',
    'camp_reg' => 'Camp registration',
    'camp_sub'  => 'Camp subscription',
    'click_here' => 'Click me! to return to home page.',
    'complete_reg' => 'Complete registration',
    'contact_details' => 'Contact details',
    'contd' => 'Continue',
    'course_info' => 'Download course information',
    'complete_sub'  => 'Complete Subscription',

    'date' => 'Date:',
    'dear' => 'Dear',

    'e' => 'E:',
    'email' => 'Email:',
    'extra_info' => 'Additional Information',

    'find_more' => 'find out more',

    'gary' => 'Gary:',

    'jan' => 'Jan:',
    'landline' => 'Landline',

    'mobile' => 'Mobile',
    'month_dates' => 'This month dates',
    'more_info' => 'Read more information >',

    'name' => 'Name',
    'new_registration' => 'New camp registration',
    'new_subscription' => 'New camp subscription',
    'next' => 'Next &gt;',
    'no_camp' => 'Selected camp does not exist.',
    'no_token' => 'Please obtain a valid token to complete payment.',
    'no_user' => 'Selected user does not exist.',

    'payment_amt' => 'Payment amount',
    'payment_type' => 'Payment type',
    'phone' => 'Phone:',
    'popular_posts' => 'Popular posts',
    'prev' => '&lt; Previous',

    'reg_complete' => 'Your registration has completed successfully. Thank you for choosing Camp Hippo.',
    'reg_success' => 'Registered successfully. Please complete the payment to complete the registration process.',
    'registration_date' => 'Registration date',
    'subscription_date' => 'Subscription date',
    'req_req' => 'Please check the course pre requisites checkboxes.',

    's_email' => 'Your email',
    's_name' => 'Your name',
    'save_error' => 'Details could not be saved. Please try later.',
    'school' => 'School',
    'sel_camp' => 'Selected camp',
    'sess_per_week' => 'The number of sessions they want to attend per week.',
    'sign_up' => 'Sign up to course',
    'sign_up_triathlons' => 'Sign up to event',
    'signup_form' =>
        array(
            'name' => 'Child name is required.',
            'address' => 'Address is required.',
            'email' => 'Email is required.',
            'mobile' => 'Mobile number is required.',
            'landline' => 'Landline number is required.',
            'school' => 'Name of the school is required.',
            'year_group' => 'Year group is required.',
        ),
    'stripe_token' => 'Stripe payment token',
    'submit' => 'Submit',
    'subscribe' => 'Subscribe',
    'subscribe_tramp' => 'Pay Trampoline Subscription',
    'subscribe_success' => 'Subscribed successfully. Please complete the payment to complete the subscription process.',
    'sessions'  => 'Sessions',
    'subscription_id'   => 'Subscription ID',
    'subscription_confirmed'    => 'Subscription confirmed',

    't' => 'T:',
    'term_attend' => 'Term they wish to attend.',
    'thank_subscribe' => 'Thank you for subscribing.',
    'time' => 'Time:',
    'terms' => 'Terms',

    'upcoming_events' => 'Upcoming events',
    'unknown'   => 'Unknown',

    'venue' => 'Venue:',
    'view_details' => 'View all details',
    'view_full' => 'View full details',

    'wished_name' => 'Wished name',

    'year' => 'Year',
    'year_events' => 'This years events',
    'year_group' => 'Year group',
);